In [1]:
from vpython import *
import hw5solution as hw
import numpy as np
#idea: add a disc in the orbital plane of the planets

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [2]:
scene1 = canvas(title="Scene 1")

<IPython.core.display.Javascript object>

In [3]:
scene2 = canvas(title="Scene 2")

<IPython.core.display.Javascript object>

In [ ]:
solplot()

In [19]:
templot(rA=rN, vA=vN)

In [17]:
t_max = 200
dt = 0.1
nsteps = int(t_max/dt)
l = 0

time, r, v = hw.integrate_orbits(dt=dt, t_max=t_max, coupled=True)
rU = np.insert(r[:,0], 2, 0, axis=1)
rN = np.insert(r[:,1], 2, 0, axis=1)
vU = np.insert(v[:,0], 2, 0, axis=1)
vN = np.insert(v[:,1], 2, 0, axis=1)
omegaU = hw.omega(vU, rU)
omegaN = hw.omega(vN, rN)



In [5]:
rA = np.insert(r[:], 2, 0, axis=2)
vA = np.insert(v[:], 2, 0, axis=2)
rA[0,0,0]

-17.301635391252759

In [18]:
neptune = sphere(pos=vector(rU[0,0],rU[0,1],0), texture=textures.neptune, make_trail=True, canvas=scene2)
uranus = sphere(pos=vector(rN[0,0],rN[0,1],0), texture=textures.uranus, make_trail=True, canvas=scene2)
sun = sphere(pos=vector(0,0,0), texture=textures.sun, make_trail=True, canvas=scene2)

planets = (uranus, neptune)

neptune.velocity = vN
uranus.velocity = vU

In [7]:
#this one works
def templot(rA, vA):
    i = 0
    while i < nsteps-1:
        rate(100)
        r0 = rA[i,0]
        v0 = vA[i,0]
        r1 = rA[i,1]
        v1 = vA[i,1]
        r2 = rA[i,2]
        v2 = vA[i,2]
        neptune.velocity = vector(v0, v1, v2)
        neptune.pos += neptune.velocity*dt
        i += 1

In [ ]:
#remaking for whole solar system
#i = time step iteration
#j = planet
#k = x, y, z
def solplot(vA=vA):
    i = 0
    while i < nsteps-1:
        j = 0
        rate(100)
        while j < len(planets)-1:
            vA0 = vA[i,j,0]
            vA1 = vA[i,j,1]
            vA2 = vA[i,j,2]
            planets[j].velocity = vector(vA0, vA1, vA2)
            planets[j].pos += planets[j].velocity*dt
            j += 1
        i += 1

In [ ]:
def solplot(vA = vA):
    i = 0
    while i < nsteps:
        j = 0
        rate(100)
        while j < len(planets)-1:
                vA0 = vA[i,j,0]
                vA1 = vA[i,j,1]
                vA2 = vA[i,j,2]
                planets[j].velocity = vector(vA0, vA1, vA2)
                planets[j].pos += planets[j].velocity*dt
                j += 1
        i += 1


In [ ]:
#old idea, doesn't work
def templot(rX):
    i = 0
    while 1:
        rate(10)
        while i < nsteps-1:
            r0 = rX[i,0]
            r1 = rX[i,1]
            r2 = rX[i,2]
            neptune.pos = vector(r0, r1, r2)
            return neptune.pos
            i += 1

In [ ]:
scene1 = canvas(title="Title")
display(scene1)

In [ ]:
while i < nsteps-1:
    rate(1)
    neptune.pos = neptune.pos + vector(v0[i], v1[i], v2[i])
    i += 1



In [ ]:
print(vN[0][0], vN[0][1], vN[0][2])
print(vN[1][0], vN[1][1], vN[1][2])
print(vN[2][0], vN[2][1], vN[2][2])
print(vN[3][0], vN[3][1], vN[3][2])
print(vN[4][0], vN[4][1], vN[4][2])
print(vN[5][0], vN[5][1], vN[5][2])
print(vN[6][0], vN[6][1], vN[6][2])
print(vN[7][0], vN[7][1], vN[7][2])
print(vN[8][0], vN[8][1], vN[8][2])

In [ ]:
v0 = vN[:,0]
v1 = vN[:,1]
v2 = vN[:,2]

In [10]:
rA[0,0]

array([-17.30163539,  -8.30441128,   0.        ])

In [13]:
rA[0,1]

array([  9.47879984, -28.52756714,   0.        ])

In [14]:
rA

array([[[-17.30163539,  -8.30441128,   0.        ],
        [  9.47879984, -28.52756714,   0.        ]],

       [[-17.36326094,  -8.17478039,   0.        ],
        [  9.36995987, -28.563501  ,   0.        ]],

       [[-17.42391669,  -8.04469294,   0.        ],
        [  9.26098371, -28.59901976,   0.        ]],

       ..., 
       [[  5.82337479,  18.32668047,   0.        ],
        [-25.41649263, -16.05129713,   0.        ]],

       [[  5.95978404,  18.2829574 ,   0.        ],
        [-25.4775852 , -15.9543139 ,   0.        ]],

       [[  6.0958624 ,  18.23821929,   0.        ],
        [-25.53830749, -15.85709881,   0.        ]]])